server:
  port: 5000


swagger:
  title: Android-Remote-Monitor
  version: 1.0.0
  name: Kitty



spring:
  application:
    name: mybatis-curdc
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: liu19990808
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

socketio:
  host: 0.0.0.0
  port: 10000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 打印sql, 方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100